services:
  mysql:
    image: mysql
    container_name: mysql-app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  backend-app:
    image: priyanshijat6701/notes-app-backend-app:latest
    container_name: backend-app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - notes-app
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend-app:
    image: priyanshijat6701/notes-app-frontend-app:latest
    container_name: frontend-app
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "80:80"
    networks:
      - notes-app
    depends_on:
      - backend-app

networks:
  notes-app:
