version: '3.8'

services:
  ai-notes-db:
    image: debabratap/ai-notes-db:latest
    container_name: ai-notes-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ai-notes-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ai-notes-backend:
    image: debabratap/ai-notes-backend:latest
    container_name: ai-notes-backend
    restart: unless-stopped
    environment:
      JWT_SECRET: op_secretkey
      PORT: 5000
      DB_HOST: ai-notes-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: notesdb
      DB_PORT: 3306
      GEMINI_API_KEY: AIzaSyCXIN8mpvGqbeE8_h2I8tMtLAfOm-uZRL0
    ports:
      - "5000:5000"
    depends_on:
      ai-notes-db:
        condition: service_healthy
    networks:
      - ai-notes-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  ai-notes-network:
    driver: bridge
