apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: frontendns  # 👈 yeh line add karni hai
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: 
        image:   
      