apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    
  clusterIP:   
  type:
    
