apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: backend-ns
  labels:
    app: database
spec:
  serviceName: "database"
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: debabratap/ai-notes-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"

        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-volume-claim

