services:
  mysql:
    image: mysql:8.0
    container_name: notes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notes_network

volumes:
  mysql_data:

networks:
  notes_network:
    driver: bridge
